import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import clsx from 'clsx'
import { Providers } from './Providers';
import Header from '@/src/components/layout/Header';
import { cn } from '@/src/lib/utils';

const poppins = Poppins({ 
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-popins'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="en" className="h-full" suppressHydrationWarning>
        <head />
        <body className={poppins.variable}>
          <Providers>
            <div className="relative flex min-h-screen flex-col">
              <Header />
              <div className="flex-1">{children}</div>
            </div>
          </Providers>
        </body>
      </html>
    </>
  )
}
